name: Validate HTML and Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install html-validate
        run: npm install --no-save html-validate

      - name: Run HTML validation
        run: npx html-validate "**/*.html"

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1